language: ruby
sudo: false
rvm:
  - 2.1.2
notifications:
  webhooks: https://www.buildheroes.com/api/projects/c0cee3957d7966d06ed5d79e951d1b12a5c480cd/builds
script: "bundle exec rake spec validate:travellers"
