name: "annismckenzie"
profile:
  twitter: "annismckenzie"
  gravatar: "d54c62322c39f914fb2ec6a31df5f314"
  current_hometown: "Leipzig, Germany"
hasbeen:
  cities:
    - "Leipzig"
    - "Hamburg"
    - "Cologne"
    - "Berlin"
    - "London"
    - "Paris"
    - "Vienna"
    - "Rostock"
    - "Gran Canaria"
    - "Munich"
    - "Potsdam"
    - "San Francisco"
    - "Los Angeles"
    - "Salzburg"
    - "Hanover"
    - "Aachen"
    - {"Miami": "Miami, FL, US"}
    - "Key West"
    - "Washington, D.C."
    - {"Nassau": "City of Nassau, The Bahamas"}
    - "Frankfurt am Main"
    - "Frankfurt an der Oder"
    - "Nuremberg"
    - "Fort Lauderdale"
    - "Dresden"
    - "Stuttgart"
    - "Görlitz"
    - "Dornbirn"
