name: "Bascht"
profile:
  web: "http://bascht.com"
  twitter: "bascht"
  gravatar: "8656dc5476c819d4dcbd932a5744122a"
hasbeen:
  cities:
    - "Leipzig"
    - "Hamburg"
    - "Oelsnitz"
    - "Cologne"
    - "Berlin"
    - "Bangkok"
    - "Shanghai"
    - "Louisville"
    - "Prague"
    - "Michigan"
    - "London"
    - "Paris"
    - "Barcelona"
    - "Vienna"
    - "Rostock"
    - "Dublin"
    - "Poznan"
    - "Wrocław"
    - "Gran Canaria"
    - "Brussels"
    - "Amsterdam"
    - {"Amerika": "Amerika, Penig, Deutschland"}
    - "Munich"
    - "Potsdam"
    - "Weimar"
    - "Ponta Delgada"
    - {"Curahuasi": "Diospi Suyana, Curahuasi"}
    - "Cusco"
    - "Ollantaytambo"
    - "Las Vegas"
    - "San Francisco"
    - "Los Angeles"
    - "Salzburg"
    - "Riga"
    - "Tallin"
    - "Helsinki"
    - "Oslo"
    - "Stockholm"
    - "Hanover"
    - "Düsseldorf"
    - "Frankfurt am Main"
    - "Frankfurt an der Oder"
    - "Nuremberg"
    - "Dresden"
    - "Stuttgart"
    - "Görlitz"
    - "Strasbourg"
    - "Galway"
    - "Grindelwald"
    - "Cork"
    - { "Washington": "Washington, D.C., DC, United States" }
    - "Philadelphia"
    - { "New York": "New York, NY, United States" }
    - "North Kingstown"
    - "Boston"
    - "Montreal"
    - "Barrie"
    - "Toronto"
    - "Kraków"
    - "Innsbruck"
    - "Tondorf"
    - "Bolzano"
    - "Zürich"
    - "Sofia"
    - "Tenerife"
