name: "cgie"
profile:
  web: "http://giessen.io"
  twitter: "cgie"
  gravatar: "e111b1854c8fe7c378a9653afbb2cb7c"
hasbeen:
  cities:
    - "Kiel"
    - "Münster"
    - "Delhi"
    - "Agra"
    - "Amsterdam"
    - "Aberystwyth"
    - "Vancouver"
    - "Whistler"
    - "Jena"
    - "Lynbgy"
    - "Kopenhagen"
    - "Sheffield"
    - "Madrid"
    - "Prag"
    - "Dirmstein"
    - "Mützenich"
    - "Bietingen"
    - "Magdeburg"
    - "Marielyst"
    - "Hamburg"
    - "Berlin"
    - "Bonn"
    - "Göttingen"
    - "München"
    - "London"
    - "Spindlermühle"
    - "Wien"
    - "Leipzig"
    - "Boberow"
    - "Ölheim"
    - "Inzell"
    - "Salzburg"
    - "Bremen"
    - "Sieseby"
    - "Flensburg"
    - "Lübeck"

