name: "Nico Hagenburger"
profile:
  web: "http://www.hagenburger.net"
  twitter: "hagenburger"
  gravatar: "28e1c6e895146e8217caf14eb56feb7b"
hasbeen:
  cities:
    - "Berlin"
    - "Mannheim"
    - "Hamburg"
    - "Köln"
    - "München"
    - "Karlsruhe"
    - "Stuttgart"
    - "Freiburg"
    - "Frankfurt am Main"
    - "Münster"
    - "Leipzig"
    - "Dresden"
    - "Potsdam"
    - "Kiel"
    - "Bremen"
    - "Bonn"
    - "Hannover"
    - "Wien"
    - "Salzburg"
    - "Innsbruck"
    - "Sopron"
    - "Liechtenstein"
    - "Zürich"
    - "Rome"
    - "Vatican City"
    - "Milano"
    - "Aosta"
    - "Meran"
    - "Venezia"
    - "Stromboli"
    - "Messina"
    - "Valetta"
    - "Tunis"
    - "Sousse"
    - "Athens"
    - "Rhodos"
    - "Istanbul"
    - "Marmaris"
    - "Bratislava"
    - "Prague"
    - "Wrocław"
    - "Kraków"
    - "Wisła"
    - "Szczecin"
    - "Trzebiatów"
    - "Rīga"
    - "Tallin"
    - "Helsinki"
    - "Oulu"
    - "Rovaniemi"
    - "Haparanda"
    - "London"
    - "Dublin"
    - "Amsterdam"
    - "Den Haag"
    - "Rotterdam"
    - "Brussels"
    - "Antwerpen"
    - "Luxembourg"
    - "Strasbourg"
    - "Dunkirk"
    - "Clermont-Ferrand"
    - "Perpignan"
    - "Bordeaux"
    - "San Sebastián"
    - "Bilbao"
    - "Barcelona"
    - "Madrid"
    - "Albufeira"
    - "Johannesburg"
    - "Kruger National Park"
    - "Pretoria"
    - "Port Elizabeth"
    - "Cape Town"
    - "La Habana"
    - "Pinar del Rio"
    - "Cienfuegos"
    - "New York"
    - "Beacon"
    - "Boston"
    - "Buffalo"
    - "Niagara Falls"
    - "Washington, D.C."
    - { "Alexandria": "Alexandria, Virginia, USA" }
    - "New Orleans"
    - "Toronto"
    - "Algonquin Provincal Park"
    - "Montréal"
    - "Ottawa"
    - { "Québec": "Quebec City, Québec, Kanada" }
    - "Baku"
    - "Beijing"
    - "Shanghai"
    - "Dalian"
    - "Bali"
    - "Singapore"
    - "Melacca"
    - "Kuala Lumpur"
    - "Taipeh"
    - "Hualien"
    - "Hong Kong"
    - "Macau"
    - "Bonifacio Global City"
    - "Manila"
    - "Palawan"
    - "Banaue"
    - "Bergamo"
    - "Stockholm"
    - "Edinburgh"
    - "Sheffield"
    - "Mexico City"
    - "Santiago de Querétaro"
    - "Peña de Bernal"
    - "San Miguel de Allende"
    - "Guanajuato Capital"
    - "Morelia"
    - "Uruapan"
    - "Manzanillo, Mexico"
    - "Colima, Mexico"
    - "Santa Monica, CA"
    - "Venice, CA"
    - "Montauk, NY"
    - "New Brunswick, NJ"
