name: "ignaces"
profile:
  web: "http://ignac.es"
  twitter: "ignaces"
  gravatar: "ad7d1cfbcc790d7c2a9bf131a66145bd"
hasbeen:
  cities:
    - {"Santa Cruz": "Santa Cruz, Chile"}
    - {"Santiago": "Santiago, Chile"}
    - "Las Condes"
    - "Arica"
    - "Iquique"
    - "Antofagasta"
    - "Copiapo"
    - "San Pedro de Atacama"
    - "Viña del Mar"
    - "Valparaiso"
    - "La Serena"
    - "Talca"
    - "Concepción"
    - "Puerto Montt"
    - "Punta Arenas"
    - "Ushuaia"
    - {"Los Angeles": "Los Angeles, CA"}
    - "Santa Monica"
    - "Long Beach"
    - "Huntington Beach"
    - "Malibu"
    - "Oxnard"
    - "Santa Clarita"
    - "Ventura"
    - {"Santa Cruz": "Santa Cruz, CA"}
    - "San Francisco"
    - "Oakland"
    - "Sunnyvale"
    - "San Jose"
    - "Cupertino"
    - "San Diego"
    - "Palo Alto"
    - "Los Gatos"
    - "Sacramento"
    - "Modesto"
    - "Phoenix"
    - "Atlanta"
    - "Dallas"
    - "Miami"
    - "Orlando"
    - "Tampa"
    - "New York"
    - "Las Vegas"
    - "Washington D.C."
    - "Baltimore"
    - "Philadelphia"
    - "Atlantic City"
    - "Chicago"
    - "Honolulu"
    - "Mililani"
    - "Montréal"
    - "Ottawa"
    - "Toronto"
    - "Ciudad de México"
    - "Lima"
    - "Buenos Aires"
    - "Mendoza"
    - "Montevideo"
    - "Blumenau"
    - "Florianapolis"
    - {"Foz do Iguaçu": "Foz do Iguaçu, Brazil"}
    - "Camboriú"
