name: "Jan"
profile:
  web: "http://jan.sh"
  twitter: "jan"
  gravatar: "68ac0d4e0f413f7c94e593bc3e94b351"
hasbeen:
  cities:
    - "Amsterdam"
    - "Bangkok"
    - "Barcelona"
    - "Berlin"
    - "Boston"
    - "Denver"
    - "Frankfurt"
    - "Freiburg"
    - "Fresno"
    - "Hamburg"
    - "Kairo"
    - "Key West"
    - "Köln"
    - "Las Vegas"
    - "Los Angeles"
    - "Madrid"
    - "Málaga"
    - "Mérida"
    - "Miami"
    - "Montreal"
    - "München"
    - "Münster"
    - "New York"
    - "Nice"
    - "Orlando"
    - "Osnabrück"
    - "Paris"
    - "Potsdam"
    - "San Francisco"
    - "Stuttgart"
    - "Toronto"
    - "Vancouver"
    - "Washington"
    - "Whistler"
    - "Wien"
