name: "jietse"
profile:
  web: ""
hasbeen:
  cities:
    - "Aachen"
    - "Brussels"
    - "Paris"
    - "Prague"
    - "Bratislava"
    - "Balaton"
    - "Krakow"
    - "Barcelona"
    - "Berlin"
    - "Siofok"
