name: "jietse"
profile:
  web: ""
hasbeen:
  cities:
    - "Aachen"
    - "Brussels"
    - "Paris"
    - "Prague"
    - "Bratislava"
    - "Balaton"
    - "Krakow"
    - "Barcelona"
    - "Berlin"
    - "Siofok"
    - "Ljubljana"
    - "Zagreb"
    - "Amsterdam"
    - "London"
    - "Cesenatico"
    - "Edinbrugh"
    - "Terragona"
    - "Santo Domigo"
    - "Quito"
    - "Guayaquil"
    - "Salou"
