name: "moonglum"
profile:
  web: ""
  twitter: "moonbeamlabs"
  gravatar: "84ac75cc9db741ff266392c83de9aa15"
hasbeen:
  cities:
    - "Aachen"
    - "Aberdeen"
    - "Aberfoyle"
    - "Amsterdam"
    - "Antalya"
    - "Bad Oeynhausen"
    - "Ballindalloch"
    - "Barcelona"
    - "Bergisch Gladbach"
    - "Berlin"
    - "Bodrum"
    - "Bonn"
    - "Boston"
    - "Brno"
    - "Buckie"
    - "Budapest"
    - "Buenos Aires"
    - {"Cambridge": "Cambridge, USA"}
    - "Cologne"
    - "Craigellachie"
    - "Crieff"
    - "Dresden"
    - "Dublin"
    - "Edinburgh"
    - {"Ephesus": "Ephesus, Selcuk, Turkey" }
    - "Fochabers"
    - "Ghent"
    - {"Goa": "Goa, India"}
    - "Grantown on Spey"
    - "Hamburg"
    - "Hanover"
    - "Heide"
    - "Helsinki"
    - "Hennstedt"
    - "Herzogenrath"
    - "Hurghada"
    - "Kennedy Space Center"
    - "Kiev"
    - "Krakow"
    - "Langeoog"
    - "Lanzarote"
    - "Lisbon"
    - "London"
    - "Lucca"
    - "Majorca"
    - "Miami Beach"
    - "Milan"
    - "Mountain View"
    - "Munich"
    - "Munster"
    - "Nuremberg"
    - "Palo Alto"
    - "Paris"
    - "Pisa"
    - "Porto de Galinhas"
    - "Poznan"
    - "Reno"
    - "Rhodes"
    - "Rome"
    - "Salzburg"
    - "San Francisco"
    - "Singapore"
    - {"Spa": "Spa, Liege, Belgium"}
    - {"Stanford": "Stanford, California"}
    - "Stirling"
    - "Tondorf"
    - "Truckee"
    - "Ulm"
    - "Vienna"
    - "Zehdenick"
