name: "Rin Raeuber"
profile:
  web: "http://rin.li"
  twitter: "rinpaku"
  gravatar: "fdc75e4cf5aa4bf67af27f5ebe19d261"
hasbeen:
  cities:
    - "Alcúdia"
    - "Amsterdam"
    - "Barcelona"
    - "Berlin"
    - "Brighton"
    - "Braga"
    - "Copenhagen"
    - "Essaouira"
    - "Essen"
    - "Gdansk"
    - "Göteborg"
    - "Hamburg"
    - "London"
    - "Milano"
    - "München"
    - "Shenzhen"
    - "Stockholm"
    - "Zurich"
