name: "schultyy"
profile:
  web: "http://ganzefolge.hasbeen.at"
  twitter: "ganzefolge"
  gravatar: "8fb4c4eea4580647ac37881cec8606aa"
hasbeen:
  cities:
    - "Hamburg"
    - "Dortmund"
    - "Cologne"
    - "Wrocław"
    - "Berlin"
    - "Arnsberg"
    - "Bochum"
    - "Hannover"
    - "Regensburg"
    - "Münster"
    - "Duisburg"
    - "Leipzig"
    - "Munich"
    - "Vienna"
    - "Amsterdam"
    - "Zandvoort"
    - "Bath"
    - "Bristol"
    
