name: "warreee"
profile:
  web: "http://warreee.be"
hasbeen:
  cities:
    - "Aachen"
    - "Brussels"
    - "Paris"
    - "Malaga"
    - "Istanbul"
    - "Madrid"
    - "Salamanca"
    - "Malaga"
    - "Prague"
    - "Bratislava"
    - "Balaton"
    - "Makarska"
    - "Krakow"
    - "Strasbourg"
    - "Barcelona"
    - "Jersey"
    - "Lisbon"
    - "Corfu"
    - "Berlin"
    - "Siofok"
    - "Verdun"

